# Generated by Django 5.1.4 on 2025-07-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_info_email_alter_info_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='name',
        ),
    ]
